service: battle-game-server
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 256
  timeout: 10

plugins:
  - serverless-offline


functions:
  getPlayer:
    handler: handlers/apigw/player/get/index.handler
    events:
      - http:
          path: player/{uuid}
          method: get
          cors: true
  postPlayer:
    handler: handlers/apigw/player/post/index.handler
    events:
      - http:
          path: player
          method: post
          cors: true
resources:
  Resources:
    PlayerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PlayerTable
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE