service: battle-game-server
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 256
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - 'Fn::GetAtt': [PlayerTable, Arn]
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:SendMessage
      Resource:
        - 'Fn::GetAtt': [BattlesQueue, Arn]
  apiKeys:
    - battleGameClientKey
  usagePlan:
    quota:
      limit: 1000
      period: MONTH
    throttle:
      burstLimit: 20
      rateLimit: 10

plugins:
  - serverless-offline


functions:
  getPlayer:
    handler: handlers/apigw/player/get/index.handler
    events:
      - http:
          path: player/{uuid}
          method: get
          private: true
          cors:
            origin: 'http://localhost:4200'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  postPlayer:
    handler: handlers/apigw/player/post/index.handler
    events:
      - http:
          path: player
          method: post
          private: true
          cors:
            origin: 'http://localhost:4200'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  submitBattle:
    handler: handlers/apigw/battle/post/index.handler
    events:
      - http:
          path: player/{uuid}/battle
          method: post
          private: true
          cors:
            origin: 'http://localhost:4200'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  getLeaderboard:
    handler: handlers/apigw/leaderboard/get/index.handler
    events:
      - http:
          path: leaderboard
          method: get
          private: true
          cors:
            origin: 'http://localhost:4200'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  processBattleWorker:
    handler: handlers/sqs/process-battle-worker.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - BattlesQueue
              - Arn
          batchSize: 10

resources:
  Resources:
    BattlesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: battles-queue
        VisibilityTimeout: 30
    PlayerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PlayerTable
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: totalStolenGold
            AttributeType: N
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
          - AttributeName: totalStolenGold
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: TotalStolenGoldIndex
            KeySchema:
              - AttributeName: totalStolenGold
                KeyType: RANGE
              - AttributeName: uuid
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE